//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteDuo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_fr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_fr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClienteDuo.Properties.Resources.fr", typeof(Resources_fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepter.
        /// </summary>
        public static string BtnAccept {
            get {
                return ResourceManager.GetString("BtnAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter l&apos;ami.
        /// </summary>
        public static string BtnAddFriend {
            get {
                return ResourceManager.GetString("BtnAddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilisateurs bloquées.
        /// </summary>
        public static string BtnBlockedUsers {
            get {
                return ResourceManager.GetString("BtnBlockedUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloquer.
        /// </summary>
        public static string BtnBlockUser {
            get {
                return ResourceManager.GetString("BtnBlockUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changer mot de passe.
        /// </summary>
        public static string BtnChangePassword {
            get {
                return ResourceManager.GetString("BtnChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuer.
        /// </summary>
        public static string BtnContinue {
            get {
                return ResourceManager.GetString("BtnContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sortir.
        /// </summary>
        public static string BtnExitLobby {
            get {
                return ResourceManager.GetString("BtnExitLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demandes d&apos;ami.
        /// </summary>
        public static string BtnFriendRequests {
            get {
                return ResourceManager.GetString("BtnFriendRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejoindre.
        /// </summary>
        public static string BtnJoin {
            get {
                return ResourceManager.GetString("BtnJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejoindre comme invité.
        /// </summary>
        public static string BtnJoinAsGuest {
            get {
                return ResourceManager.GetString("BtnJoinAsGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejoindre groupe.
        /// </summary>
        public static string BtnJoinParty {
            get {
                return ResourceManager.GetString("BtnJoinParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expulser.
        /// </summary>
        public static string BtnKick {
            get {
                return ResourceManager.GetString("BtnKick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejoindre.
        /// </summary>
        public static string BtnLogin {
            get {
                return ResourceManager.GetString("BtnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier le profil.
        /// </summary>
        public static string BtnModifyProfile {
            get {
                return ResourceManager.GetString("BtnModifyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouvelle compte.
        /// </summary>
        public static string BtnNewAccount {
            get {
                return ResourceManager.GetString("BtnNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouvel groupe.
        /// </summary>
        public static string BtnNewParty {
            get {
                return ResourceManager.GetString("BtnNewParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        public static string BtnProfile {
            get {
                return ResourceManager.GetString("BtnProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sortir.
        /// </summary>
        public static string BtnQuitGame {
            get {
                return ResourceManager.GetString("BtnQuitGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refuser.
        /// </summary>
        public static string BtnReject {
            get {
                return ResourceManager.GetString("BtnReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commencer partie.
        /// </summary>
        public static string BtnStartGame {
            get {
                return ResourceManager.GetString("BtnStartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debloquer.
        /// </summary>
        public static string BtnUnblockUser {
            get {
                return ResourceManager.GetString("BtnUnblockUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suprimer l&apos;amitié.
        /// </summary>
        public static string BtnUnfriend {
            get {
                return ResourceManager.GetString("BtnUnfriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous etes déjà ami de ce joueur.
        /// </summary>
        public static string DlgAlreadyFriends {
            get {
                return ResourceManager.GetString("DlgAlreadyFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Êtes-vous sûr de vouloir bloquer cet utilisateur ? Vous ne pourrez rejoindre aucun groupe auquel participe ce joueur, il ne pourra pas vous ajouter en tant qu&apos;ami et il ne pourra pas rejoindre votre partie. à l&apos;avenir.
        /// </summary>
        public static string DlgBlockConfirmation {
            get {
                return ResourceManager.GetString("DlgBlockConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;utilisateur a eté bloqué.
        /// </summary>
        public static string DlgBlockedUser {
            get {
                return ResourceManager.GetString("DlgBlockedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il y avait un échec de connection avec le service, essayer autre fois à plus tard.
        /// </summary>
        public static string DlgConnectionError {
            get {
                return ResourceManager.GetString("DlgConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;e-mail doit contenir moins de 30 caractères et un format valide (----@domain.com).
        /// </summary>
        public static string DlgEmailInvalid {
            get {
                return ResourceManager.GetString("DlgEmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;e-mail fourni n&apos;est associé à aucun compte.
        /// </summary>
        public static string DlgEmailNonExistent {
            get {
                return ResourceManager.GetString("DlgEmailNonExistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An account with that email is already registered.
        /// </summary>
        public static string DlgEmailTaken {
            get {
                return ResourceManager.GetString("DlgEmailTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tous les champes doivent être remplis.
        /// </summary>
        public static string DlgEmptyFields {
            get {
                return ResourceManager.GetString("DlgEmptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;expulsion du joueur n&apos;était pas possible, definez une raison d&apos;expulsion s&apos;il vous plait.
        /// </summary>
        public static string DlgEmptyKickingReason {
            get {
                return ResourceManager.GetString("DlgEmptyKickingReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Étes vous sur de sortir du jeu? Vous ne pourrez rentrer jusqu&apos;a il est fini.
        /// </summary>
        public static string DlgExitConfirmation {
            get {
                return ResourceManager.GetString("DlgExitConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Etes vous sur de sortir du jeu? Vous ne pourrez rentrer autres fois.
        /// </summary>
        public static string DlgExitMatchConfirmation {
            get {
                return ResourceManager.GetString("DlgExitMatchConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom d&apos;utilisateur ou courriel incorrectes.
        /// </summary>
        public static string DlgFailedLogin {
            get {
                return ResourceManager.GetString("DlgFailedLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une demande d&apos;amitié est déjà envoyée.
        /// </summary>
        public static string DlgFriendRequestAlreadySent {
            get {
                return ResourceManager.GetString("DlgFriendRequestAlreadySent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous avez refusée cette demande d&apos;amitié.
        /// </summary>
        public static string DlgFriendRequestDeleted {
            get {
                return ResourceManager.GetString("DlgFriendRequestDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il y avait un echec en envoyant de la demande d&apos;ami.
        /// </summary>
        public static string DlgFriendRequestError {
            get {
                return ResourceManager.GetString("DlgFriendRequestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demande d&apos;amitié envoyée.
        /// </summary>
        public static string DlgFriendRequestSent {
            get {
                return ResourceManager.GetString("DlgFriendRequestSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous ne pouvez pas envoyer un demande d&apos;amitié a vous même.
        /// </summary>
        public static string DlgFriendYourself {
            get {
                return ResourceManager.GetString("DlgFriendYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le groupe est rempli, réessayer à plus tard.
        /// </summary>
        public static string DlgFullParty {
            get {
                return ResourceManager.GetString("DlgFullParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le host a abandonnée le jeu.
        /// </summary>
        public static string DlgHostHasClosedTheParty {
            get {
                return ResourceManager.GetString("DlgHostHasClosedTheParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La mot de passe dois contenir au moins: 8 caractères, un caractèr spéciaux(!@?#$&amp;$°¬|/%*), et des lettres majuscules et minuscules.
        /// </summary>
        public static string DlgInsecurePassword {
            get {
                return ResourceManager.GetString("DlgInsecurePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format invalide.
        /// </summary>
        public static string DlgInvalidFormat {
            get {
                return ResourceManager.GetString("DlgInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le code de groupe doit être un numéro de 4 chiffres comme maximum.
        /// </summary>
        public static string DlgInvalidPartyCodeFormat {
            get {
                return ResourceManager.GetString("DlgInvalidPartyCodeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il est désormais actif.
        /// </summary>
        public static string DlgIsNowActive {
            get {
                return ResourceManager.GetString("DlgIsNowActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous avez été expulsé du jeu. .
        /// </summary>
        public static string DlgKickedPlayer {
            get {
                return ResourceManager.GetString("DlgKickedPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La raison de votre expulsion est: .
        /// </summary>
        public static string DlgKickingReason {
            get {
                return ResourceManager.GetString("DlgKickingReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Des messages peuvent contenir seulement 250 caractères.
        /// </summary>
        public static string DlgMessageMaxCharacters {
            get {
                return ResourceManager.GetString("DlgMessageMaxCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nom d&apos;utilisater est enregistré avec succès.
        /// </summary>
        public static string DlgNewAccountSuccess {
            get {
                return ResourceManager.GetString("DlgNewAccountSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Échec en commençant, il faut que le Lobby a au moins 2 jeueurs.
        /// </summary>
        public static string DlgNotEnoughPlayers {
            get {
                return ResourceManager.GetString("DlgNotEnoughPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous êtes maintenant amis.
        /// </summary>
        public static string DlgNowFriends {
            get {
                return ResourceManager.GetString("DlgNowFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le code de groupe est incorrecte.
        /// </summary>
        public static string DlgPartyNotFound {
            get {
                return ResourceManager.GetString("DlgPartyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le mot de passe et le mot de passe de confirmation doivent correspondre.
        /// </summary>
        public static string DlgPasswordDoesNotMatch {
            get {
                return ResourceManager.GetString("DlgPasswordDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;image du profil a eté mis à jour.
        /// </summary>
        public static string DlgProfilePictureUpdated {
            get {
                return ResourceManager.GetString("DlgProfilePictureUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il y avait un échec de connection avec le service, réessayer à plus tard.
        /// </summary>
        public static string DlgServiceException {
            get {
                return ResourceManager.GetString("DlgServiceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilisateur debloquée avec succès.
        /// </summary>
        public static string DlgUnblockSuccess {
            get {
                return ResourceManager.GetString("DlgUnblockSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous n&apos;êtes plus amis.
        /// </summary>
        public static string DlgUnfriend {
            get {
                return ResourceManager.GetString("DlgUnfriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Êtes-vous sûr de vouloir supprimer cet utilisateur de vos amis ?.
        /// </summary>
        public static string DlgUnfriendConfirmation {
            get {
                return ResourceManager.GetString("DlgUnfriendConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une session est déjà active.
        /// </summary>
        public static string DlgUserAlreadyLoggedIn {
            get {
                return ResourceManager.GetString("DlgUserAlreadyLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous ne pouvez pas rejoindre ce groupe, un utilisateur que vous avez bloqué ou que vous avez bloqué est dans le groupe.
        /// </summary>
        public static string DlgUserBlockedInParty {
            get {
                return ResourceManager.GetString("DlgUserBlockedInParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nom d&apos;utilisateur n&apos;existe pas.
        /// </summary>
        public static string DlgUsernameDoesNotExist {
            get {
                return ResourceManager.GetString("DlgUsernameDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nom d&apos;utilisateur doit contenir des valeurs alphanumériques, au moins 3 caractères, un maximum de 14 et ne pas contenir de mot &quot;guest&quot;.
        /// </summary>
        public static string DlgUsernameInvalid {
            get {
                return ResourceManager.GetString("DlgUsernameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les nombre de caractéres dans un nom d&apos;utilisateur est 30 comme maximum.
        /// </summary>
        public static string DlgUsernameMaxCharacters {
            get {
                return ResourceManager.GetString("DlgUsernameMaxCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nom d&apos;utilisater est déjà enregistré.
        /// </summary>
        public static string DlgUsernameTaken {
            get {
                return ResourceManager.GetString("DlgUsernameTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code erroné.
        /// </summary>
        public static string DlgWrongCode {
            get {
                return ResourceManager.GetString("DlgWrongCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter nouvel ami.
        /// </summary>
        public static string LblAddNewFriend {
            get {
                return ResourceManager.GetString("LblAddNewFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En calculant des resultats....
        /// </summary>
        public static string LblCalculatingResults {
            get {
                return ResourceManager.GetString("LblCalculatingResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartes restantes.
        /// </summary>
        public static string LblCardsLeft {
            get {
                return ResourceManager.GetString("LblCardsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string LblChat {
            get {
                return ResourceManager.GetString("LblChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmer nouvelle mot de passe.
        /// </summary>
        public static string LblConfirmNewPassword {
            get {
                return ResourceManager.GetString("LblConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmer mot de passe.
        /// </summary>
        public static string LblConfirmPassword {
            get {
                return ResourceManager.GetString("LblConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courriel.
        /// </summary>
        public static string LblEmail {
            get {
                return ResourceManager.GetString("LblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amis.
        /// </summary>
        public static string LblFriends {
            get {
                return ResourceManager.GetString("LblFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration de jeu.
        /// </summary>
        public static string LblGameSettings {
            get {
                return ResourceManager.GetString("LblGameSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nous vous enverrons un email pour réinitialiser votre mot de passe.
        /// </summary>
        public static string LblInfoResetPassword {
            get {
                return ResourceManager.GetString("LblInfoResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom temporel.
        /// </summary>
        public static string LblInGameUsername {
            get {
                return ResourceManager.GetString("LblInGameUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaderboard.
        /// </summary>
        public static string LblLeaderboard {
            get {
                return ResourceManager.GetString("LblLeaderboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeu fini.
        /// </summary>
        public static string LblMatchEnd {
            get {
                return ResourceManager.GetString("LblMatchEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string LblMyProfile {
            get {
                return ResourceManager.GetString("LblMyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouvelle mot de passe.
        /// </summary>
        public static string LblNewPassword {
            get {
                return ResourceManager.GetString("LblNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code de groupe.
        /// </summary>
        public static string LblPartyCode {
            get {
                return ResourceManager.GetString("LblPartyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe.
        /// </summary>
        public static string LblPassword {
            get {
                return ResourceManager.GetString("LblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to J&apos;ai oubliée ma mot de passe.
        /// </summary>
        public static string LblPasswordForgotten {
            get {
                return ResourceManager.GetString("LblPasswordForgotten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joueurs.
        /// </summary>
        public static string LblPlayers {
            get {
                return ResourceManager.GetString("LblPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prêt.
        /// </summary>
        public static string LblReady {
            get {
                return ResourceManager.GetString("LblReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisissez une raison (Optional).
        /// </summary>
        public static string LblSelectReason {
            get {
                return ResourceManager.GetString("LblSelectReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Victoires totales.
        /// </summary>
        public static string LblTotalWins {
            get {
                return ResourceManager.GetString("LblTotalWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prix.
        /// </summary>
        public static string LblTrophies {
            get {
                return ResourceManager.GetString("LblTrophies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom d&apos;utilisateur.
        /// </summary>
        public static string LblUsername {
            get {
                return ResourceManager.GetString("LblUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vainqueur.
        /// </summary>
        public static string LblWinner {
            get {
                return ResourceManager.GetString("LblWinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tricherie.
        /// </summary>
        public static string RsnCheating {
            get {
                return ResourceManager.GetString("RsnCheating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comportment inapproprié.
        /// </summary>
        public static string RsnInappropriateBehaviour {
            get {
                return ResourceManager.GetString("RsnInappropriateBehaviour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spam.
        /// </summary>
        public static string RsnSpam {
            get {
                return ResourceManager.GetString("RsnSpam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerte.
        /// </summary>
        public static string TitleAlert {
            get {
                return ResourceManager.GetString("TitleAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expulser joueur.
        /// </summary>
        public static string TitleKickPlayer {
            get {
                return ResourceManager.GetString("TitleKickPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher.
        /// </summary>
        public static string TitleLauncher {
            get {
                return ResourceManager.GetString("TitleLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string TitleLogin {
            get {
                return ResourceManager.GetString("TitleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouvelle compte.
        /// </summary>
        public static string TitleNewAccount {
            get {
                return ResourceManager.GetString("TitleNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réinitialisation du mot de passe.
        /// </summary>
        public static string TitlePasswordReset {
            get {
                return ResourceManager.GetString("TitlePasswordReset", resourceCulture);
            }
        }
    }
}
