//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteDuo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClienteDuo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string BtnAccept {
            get {
                return ResourceManager.GetString("BtnAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Friend.
        /// </summary>
        public static string BtnAddFriend {
            get {
                return ResourceManager.GetString("BtnAddFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked Users.
        /// </summary>
        public static string BtnBlockedUsers {
            get {
                return ResourceManager.GetString("BtnBlockedUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        public static string BtnBlockUser {
            get {
                return ResourceManager.GetString("BtnBlockUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string BtnChangePassword {
            get {
                return ResourceManager.GetString("BtnChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string BtnContinue {
            get {
                return ResourceManager.GetString("BtnContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Lobby.
        /// </summary>
        public static string BtnExitLobby {
            get {
                return ResourceManager.GetString("BtnExitLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend Requests.
        /// </summary>
        public static string BtnFriendRequests {
            get {
                return ResourceManager.GetString("BtnFriendRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        public static string BtnJoin {
            get {
                return ResourceManager.GetString("BtnJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join As Guest.
        /// </summary>
        public static string BtnJoinAsGuest {
            get {
                return ResourceManager.GetString("BtnJoinAsGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Party.
        /// </summary>
        public static string BtnJoinParty {
            get {
                return ResourceManager.GetString("BtnJoinParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kick.
        /// </summary>
        public static string BtnKick {
            get {
                return ResourceManager.GetString("BtnKick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string BtnLogin {
            get {
                return ResourceManager.GetString("BtnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string BtnLogOut {
            get {
                return ResourceManager.GetString("BtnLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify Profile.
        /// </summary>
        public static string BtnModifyProfile {
            get {
                return ResourceManager.GetString("BtnModifyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Account.
        /// </summary>
        public static string BtnNewAccount {
            get {
                return ResourceManager.GetString("BtnNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Party.
        /// </summary>
        public static string BtnNewParty {
            get {
                return ResourceManager.GetString("BtnNewParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string BtnProfile {
            get {
                return ResourceManager.GetString("BtnProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit Game.
        /// </summary>
        public static string BtnQuitGame {
            get {
                return ResourceManager.GetString("BtnQuitGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string BtnReject {
            get {
                return ResourceManager.GetString("BtnReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Game.
        /// </summary>
        public static string BtnStartGame {
            get {
                return ResourceManager.GetString("BtnStartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unblock.
        /// </summary>
        public static string BtnUnblockUser {
            get {
                return ResourceManager.GetString("BtnUnblockUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfriend.
        /// </summary>
        public static string BtnUnfriend {
            get {
                return ResourceManager.GetString("BtnUnfriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user is your friend already.
        /// </summary>
        public static string DlgAlreadyFriends {
            get {
                return ResourceManager.GetString("DlgAlreadyFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to block this user? you won&apos;t be able to join any party where this player is in, he won&apos;t be able to add you as a friend, and he won&apos;t be able to join your game in the future.
        /// </summary>
        public static string DlgBlockConfirmation {
            get {
                return ResourceManager.GetString("DlgBlockConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user has been blocked.
        /// </summary>
        public static string DlgBlockedUser {
            get {
                return ResourceManager.GetString("DlgBlockedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error connecting with the service, try again later.
        /// </summary>
        public static string DlgConnectionError {
            get {
                return ResourceManager.GetString("DlgConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t block this user, try again later.
        /// </summary>
        public static string DlgCouldntBlockUser {
            get {
                return ResourceManager.GetString("DlgCouldntBlockUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email must have less than 30 characters and a valid format (----@domain.com).
        /// </summary>
        public static string DlgEmailInvalid {
            get {
                return ResourceManager.GetString("DlgEmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email provided is not associated with any account.
        /// </summary>
        public static string DlgEmailNonExistent {
            get {
                return ResourceManager.GetString("DlgEmailNonExistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An account with that email is already registered.
        /// </summary>
        public static string DlgEmailTaken {
            get {
                return ResourceManager.GetString("DlgEmailTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields must be completed.
        /// </summary>
        public static string DlgEmptyFields {
            get {
                return ResourceManager.GetString("DlgEmptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t KickPlayer, please define a reason to kick him.
        /// </summary>
        public static string DlgEmptyKickingReason {
            get {
                return ResourceManager.GetString("DlgEmptyKickingReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit the match? You will not be able to join again until it is over.
        /// </summary>
        public static string DlgExitConfirmation {
            get {
                return ResourceManager.GetString("DlgExitConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Are you sure you want to quit this match? You will not be able to return until it&apos;s over.
        /// </summary>
        public static string DlgExitMatchConfirmation {
            get {
                return ResourceManager.GetString("DlgExitMatchConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        public static string DlgFailedLogin {
            get {
                return ResourceManager.GetString("DlgFailedLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A friend request has already been sent.
        /// </summary>
        public static string DlgFriendRequestAlreadySent {
            get {
                return ResourceManager.GetString("DlgFriendRequestAlreadySent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have rejected this request.
        /// </summary>
        public static string DlgFriendRequestDeleted {
            get {
                return ResourceManager.GetString("DlgFriendRequestDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error sending friend request to this user.
        /// </summary>
        public static string DlgFriendRequestError {
            get {
                return ResourceManager.GetString("DlgFriendRequestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend request sent.
        /// </summary>
        public static string DlgFriendRequestSent {
            get {
                return ResourceManager.GetString("DlgFriendRequestSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot send a friend request to yourself.
        /// </summary>
        public static string DlgFriendYourself {
            get {
                return ResourceManager.GetString("DlgFriendYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The party is already full, try again later.
        /// </summary>
        public static string DlgFullParty {
            get {
                return ResourceManager.GetString("DlgFullParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host has left the party.
        /// </summary>
        public static string DlgHostHasClosedTheParty {
            get {
                return ResourceManager.GetString("DlgHostHasClosedTheParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password needs to contain at least: 8 characters, one special symbol(!@?#$&amp;$°¬|/%*), one uppercase and lowercase letter, and a maximum of 16 characters.
        /// </summary>
        public static string DlgInsecurePassword {
            get {
                return ResourceManager.GetString("DlgInsecurePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format.
        /// </summary>
        public static string DlgInvalidFormat {
            get {
                return ResourceManager.GetString("DlgInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party code needs to be a number with a max of 4 digits.
        /// </summary>
        public static string DlgInvalidPartyCodeFormat {
            get {
                return ResourceManager.GetString("DlgInvalidPartyCodeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is now active.
        /// </summary>
        public static string DlgIsNowActive {
            get {
                return ResourceManager.GetString("DlgIsNowActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been kicked from the game. .
        /// </summary>
        public static string DlgKickedPlayer {
            get {
                return ResourceManager.GetString("DlgKickedPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reason of the kicking is: .
        /// </summary>
        public static string DlgKickingReason {
            get {
                return ResourceManager.GetString("DlgKickingReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are banned, and you can no longer log into your account.
        /// </summary>
        public static string DlgLoginBanned {
            get {
                return ResourceManager.GetString("DlgLoginBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close this session?.
        /// </summary>
        public static string DlgLogOutConfirmation {
            get {
                return ResourceManager.GetString("DlgLogOutConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A message can only contain 250 characters.
        /// </summary>
        public static string DlgMessageMaxCharacters {
            get {
                return ResourceManager.GetString("DlgMessageMaxCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user has been registered succesfully.
        /// </summary>
        public static string DlgNewAccountSuccess {
            get {
                return ResourceManager.GetString("DlgNewAccountSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot start the game, lobby must have at least 2 players.
        /// </summary>
        public static string DlgNotEnoughPlayers {
            get {
                return ResourceManager.GetString("DlgNotEnoughPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are now friends!.
        /// </summary>
        public static string DlgNowFriends {
            get {
                return ResourceManager.GetString("DlgNowFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The party code is incorrect.
        /// </summary>
        public static string DlgPartyNotFound {
            get {
                return ResourceManager.GetString("DlgPartyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and and confirm password must match.
        /// </summary>
        public static string DlgPasswordDoesNotMatch {
            get {
                return ResourceManager.GetString("DlgPasswordDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your profile picture could&apos;t be updated, try again later.
        /// </summary>
        public static string DlgProfilePictureNotUpdated {
            get {
                return ResourceManager.GetString("DlgProfilePictureNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile picture has been updated.
        /// </summary>
        public static string DlgProfilePictureUpdated {
            get {
                return ResourceManager.GetString("DlgProfilePictureUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error connecting with the service, try again later.
        /// </summary>
        public static string DlgServiceException {
            get {
                return ResourceManager.GetString("DlgServiceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User succesfully unblocked.
        /// </summary>
        public static string DlgUnblockSuccess {
            get {
                return ResourceManager.GetString("DlgUnblockSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are no longer friends.
        /// </summary>
        public static string DlgUnfriend {
            get {
                return ResourceManager.GetString("DlgUnfriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this user from your friends?.
        /// </summary>
        public static string DlgUnfriendConfirmation {
            get {
                return ResourceManager.GetString("DlgUnfriendConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A session is already active.
        /// </summary>
        public static string DlgUserAlreadyLoggedIn {
            get {
                return ResourceManager.GetString("DlgUserAlreadyLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due to multiple reports this user has been banned.
        /// </summary>
        public static string DlgUserBanned {
            get {
                return ResourceManager.GetString("DlgUserBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot join this party, a user you have blocked or has you blocked is in party.
        /// </summary>
        public static string DlgUserBlockedInParty {
            get {
                return ResourceManager.GetString("DlgUserBlockedInParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username does not exist.
        /// </summary>
        public static string DlgUsernameDoesNotExist {
            get {
                return ResourceManager.GetString("DlgUsernameDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username must contain alphanumeric values, at least 3 characters, a maximum of 14 and not contain &quot;guest&quot; word.
        /// </summary>
        public static string DlgUsernameInvalid {
            get {
                return ResourceManager.GetString("DlgUsernameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max characters for username is 30.
        /// </summary>
        public static string DlgUsernameMaxCharacters {
            get {
                return ResourceManager.GetString("DlgUsernameMaxCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is already taken.
        /// </summary>
        public static string DlgUsernameTaken {
            get {
                return ResourceManager.GetString("DlgUsernameTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong code.
        /// </summary>
        public static string DlgWrongCode {
            get {
                return ResourceManager.GetString("DlgWrongCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add friend.
        /// </summary>
        public static string LblAddNewFriend {
            get {
                return ResourceManager.GetString("LblAddNewFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating results....
        /// </summary>
        public static string LblCalculatingResults {
            get {
                return ResourceManager.GetString("LblCalculatingResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards left.
        /// </summary>
        public static string LblCardsLeft {
            get {
                return ResourceManager.GetString("LblCardsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string LblChat {
            get {
                return ResourceManager.GetString("LblChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string LblCode {
            get {
                return ResourceManager.GetString("LblCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        public static string LblConfirmNewPassword {
            get {
                return ResourceManager.GetString("LblConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string LblConfirmPassword {
            get {
                return ResourceManager.GetString("LblConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string LblEmail {
            get {
                return ResourceManager.GetString("LblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        public static string LblFriends {
            get {
                return ResourceManager.GetString("LblFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Settings.
        /// </summary>
        public static string LblGameSettings {
            get {
                return ResourceManager.GetString("LblGameSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will send you an email to reset your password.
        /// </summary>
        public static string LblInfoResetPassword {
            get {
                return ResourceManager.GetString("LblInfoResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary Username.
        /// </summary>
        public static string LblInGameUsername {
            get {
                return ResourceManager.GetString("LblInGameUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaderboard.
        /// </summary>
        public static string LblLeaderboard {
            get {
                return ResourceManager.GetString("LblLeaderboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Over.
        /// </summary>
        public static string LblMatchEnd {
            get {
                return ResourceManager.GetString("LblMatchEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string LblMyProfile {
            get {
                return ResourceManager.GetString("LblMyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string LblNewPassword {
            get {
                return ResourceManager.GetString("LblNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Code.
        /// </summary>
        public static string LblPartyCode {
            get {
                return ResourceManager.GetString("LblPartyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LblPassword {
            get {
                return ResourceManager.GetString("LblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I forgot my password.
        /// </summary>
        public static string LblPasswordForgotten {
            get {
                return ResourceManager.GetString("LblPasswordForgotten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        public static string LblPlayers {
            get {
                return ResourceManager.GetString("LblPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string LblReady {
            get {
                return ResourceManager.GetString("LblReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a reason (Optional).
        /// </summary>
        public static string LblSelectReason {
            get {
                return ResourceManager.GetString("LblSelectReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Wins.
        /// </summary>
        public static string LblTotalWins {
            get {
                return ResourceManager.GetString("LblTotalWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trophies.
        /// </summary>
        public static string LblTrophies {
            get {
                return ResourceManager.GetString("LblTrophies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string LblUsername {
            get {
                return ResourceManager.GetString("LblUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winner.
        /// </summary>
        public static string LblWinner {
            get {
                return ResourceManager.GetString("LblWinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheating.
        /// </summary>
        public static string RsnCheating {
            get {
                return ResourceManager.GetString("RsnCheating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inappropriate Behaviour.
        /// </summary>
        public static string RsnInappropriateBehaviour {
            get {
                return ResourceManager.GetString("RsnInappropriateBehaviour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spam.
        /// </summary>
        public static string RsnSpam {
            get {
                return ResourceManager.GetString("RsnSpam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        public static string TitleAlert {
            get {
                return ResourceManager.GetString("TitleAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kick player.
        /// </summary>
        public static string TitleKickPlayer {
            get {
                return ResourceManager.GetString("TitleKickPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher.
        /// </summary>
        public static string TitleLauncher {
            get {
                return ResourceManager.GetString("TitleLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string TitleLogin {
            get {
                return ResourceManager.GetString("TitleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Account.
        /// </summary>
        public static string TitleNewAccount {
            get {
                return ResourceManager.GetString("TitleNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Reset.
        /// </summary>
        public static string TitlePasswordReset {
            get {
                return ResourceManager.GetString("TitlePasswordReset", resourceCulture);
            }
        }
    }
}
